import type { Level } from './types';

export const DEFAULT_LEVELS: Level[] = [
  {
    id: 'l1',
    sub: '경지',
    rank: '1',
    name: '삼류',
    aliases: [],
    desc: '무공에 막 입문한 수준. 내공을 담아 운기할 수 있는 정도.',
    conditions: '',
    notes: '',
  },
  {
    id: 'l2',
    sub: '경지',
    rank: '2',
    name: '이류',
    aliases: [],
    desc: '내공심법을 익혔으나 실전 적용은 미숙한 수준. 초식의 형을 어느 정도 구사할 수 있으며 일반 성인 장정보다 훨씬 강함.',
    conditions: '',
    notes: '',
  },
  {
    id: 'l3',
    sub: '경지',
    rank: '3',
    name: '일류',
    aliases: [],
    desc: '무공을 제대로 익히고 능숙하게 펼칠 수 있는 수준. 검기 구사가 가능한 단계. 이류와는 격이 다름.',
    conditions: '',
    notes: '',
  },
  {
    id: 'l4',
    sub: '경지',
    rank: '4',
    name: '절정',
    aliases: [],
    desc: '대문파의 장문인이나 원로급이 도달하는 경지. 강기 구사가 가능한 단계.',
    conditions: '',
    notes: '초입 → 완숙 → 극으로 세분화. 1갑자(60년) 이상의 내공이 절정 고수의 기준.',
  },
  {
    id: 'l5',
    sub: '경지',
    rank: '5',
    name: '초절정',
    aliases: [],
    desc: '절정을 넘어선 초인의 입문 단계. 검강이 검기를 압도하며 절정 고수는 일격에 격퇴되기도 함.',
    conditions: '초절정 전후부터 육감이 발달하여 상대의 허점을 통찰하는 능력이 생김.',
    notes: '초입 → 완숙 → 극으로 세분화.',
  },
  {
    id: 'l6',
    sub: '경지',
    rank: '6',
    name: '화경',
    aliases: ['극마', '팔성', '조화경', '천위'],
    desc: '벽을 넘은 자. 무공이 몸에 완전히 스며든 경지. 검강에 제한이 없고 이기어검술과 격공섭물을 자유자재로 펼치며 손짓만으로도 무공을 구사할 수 있음.',
    conditions: '주요 문파의 장문인, 가주, 궁주 등 거대 세력 수장급이 도달하는 경지. 단신으로 대문파 하나를 상대할 수 있는 수준.',
    notes: '보통 우내십존(천하십대고수)을 화경의 경지로 설정하는 경우가 많음.',
  },
  {
    id: 'l7',
    sub: '경지',
    rank: '7',
    name: '현경',
    aliases: ['조율경', '탈마', '육천', '입신경'],
    desc: '현묘한 경지. 진기와 강기에 완전히 통달하여 무의 이치를 벗어나 마음이 가는 대로 최상의 묘수를 펼치는 경지.',
    conditions: '초입~완숙: 오대고수급. 중원 전체를 통틀어 10명 채 되지 않음.\n극: 전설적 인물로 표현되는 수준.',
    notes: '화경의 고수 둘 이상이 모여야 겨우 상대 가능한 수준.',
  },
  {
    id: 'l8',
    sub: '경지',
    rank: '8',
    name: '생사경',
    aliases: ['초마경', '외경', '신화경'],
    desc: '삶과 죽음을 초월하는 경지. 수명의 한계를 초월하며 먹지 않아도 숨만 쉬면 살 수 있고 늙지 않고 병들지 않음.',
    conditions: '초입: 무림 세력 일부를 단독으로 상대 가능. 무형검 사용 가능.\n완숙~극: 인간의 범주를 완전히 벗어난 존재로 취급됨.',
    notes: '천년에 한번 나올까 말까 한 전설의 경지.',
  },
  {
    id: 'l9',
    sub: '경지',
    rank: '9',
    name: '자연경',
    aliases: ['신화경', '초월경'],
    desc: '무림에서 상상의 경지로 취급되는 단계. 도달한 자가 극소수에 불과하며 전설로만 내려오는 무위의 끝.',
    conditions: '자연의 기를 몸에 담아 무한에 가까운 내공 보유. 심검, 심권, 심도 사용 가능.\n완숙~극: 타인이 죽이지 않는 이상 수명으로 죽지 않고 늙지 않음.',
    notes: '',
  },
  {
    id: 'l10',
    sub: '경지',
    rank: '10',
    name: '공허경',
    aliases: [],
    desc: '자연경을 뛰어넘은 경지. 공허, 우주의 기운을 다루며 몸에 담을 수 있는 단계. 완벽한 무한의 내공을 보유.',
    conditions: '공간검, 공간이동술 사용 가능. 특정 공간을 소멸시킬 수 있음.',
    notes: '',
  },
  {
    id: 'l11',
    sub: '경지',
    rank: '11',
    name: '여의경',
    aliases: [],
    desc: '완전한 신의 경지. 도달한 자가 거의 존재하지 않는 궁극의 무위.',
    conditions: '우주의 경지를 깨달아 의지대로 자유로이 다룸. 공간의 제약이 일체 없음. 시간을 멈출 수 있는 것으로 추정.',
    notes: '여의: 무한한 의지로 못하는 것이 없음.',
  },
  {
    id: 'l12',
    sub: '경지',
    rank: '12',
    name: '탈각 / 등선 / 우화등선',
    aliases: [],
    desc: '인간의 경계를 넘어서는 것. 무로써 도를 이뤄 등선하는 궁극의 경지. 육신을 버리고 선계로 나아감.',
    conditions: '',
    notes: '',
  },
  {
    id: 's1',
    sub: '검도',
    rank: '1',
    name: '검기',
    aliases: ['검기'],
    desc: '검에서 뿜어져 나오는 기운으로 상대에게 상처를 입히는 단계. 일류 고수부터 구사 가능.',
    conditions: '',
    notes: '',
  },
  {
    id: 's2',
    sub: '검도',
    rank: '2',
    name: '검사',
    aliases: [],
    desc: '검기가 실처럼 가늘고 길게 이어지는 단계.',
    conditions: '',
    notes: '',
  },
  {
    id: 's3',
    sub: '검도',
    rank: '3',
    name: '검강',
    aliases: ['검강'],
    desc: '검기가 강철처럼 굳어지는 단계. 초절정~화경의 상징적인 기술.',
    conditions: '',
    notes: '',
  },
  {
    id: 's4',
    sub: '검도',
    rank: '4',
    name: '검환',
    aliases: ['검환'],
    desc: '검강을 압축하여 구슬 형태로 방출하는 단계. 화경 고수의 상징적 기술.',
    conditions: '',
    notes: '',
  },
  {
    id: 's5',
    sub: '검도',
    rank: '5',
    name: '이기어검술',
    aliases: [],
    desc: '기로 검을 부려 검 없이도 검술을 펼치는 단계.',
    conditions: '',
    notes: '',
  },
  {
    id: 's6',
    sub: '검도',
    rank: '6',
    name: '이기어검강',
    aliases: [],
    desc: '기로 검강을 부리는 단계. 이기어검술보다 한 단계 높은 경지.',
    conditions: '',
    notes: '',
  },
  {
    id: 's7',
    sub: '검도',
    rank: '7',
    name: '신검합일',
    aliases: [],
    desc: '몸과 검이 하나가 되는 경지. 검을 매개체로 하는 무공의 정점.',
    conditions: '',
    notes: '',
  },
  {
    id: 's8',
    sub: '검도',
    rank: '8',
    name: '심검 / 무형검',
    aliases: [],
    desc: '마음으로 검을 다루는 궁극의 경지. 현경~생사경부터 구사 가능.',
    conditions: '',
    notes: '',
  },
  { id: 'c3', sub: '성취', rank: '', name: '만류귀종', aliases: [], desc: '모든 흐름이 하나의 근원으로 돌아감.', conditions: '', notes: '' },
  { id: 'c4', sub: '성취', rank: '', name: '반로환동', aliases: [], desc: '무공이 경지에 이르러 몸이 최적화되며 어린아이처럼 젊어지는 현상.', conditions: '', notes: '' },
  { id: 'c5', sub: '성취', rank: '', name: '환골탈태', aliases: [], desc: '뼈와 근육이 무예에 최적화되어 완전히 새롭게 바뀌는 과정.', conditions: '', notes: '' },
  { id: 'c8', sub: '방어', rank: '', name: '금강불괴', aliases: [], desc: '어떤 검이나 무기를 맞아도 다치지 않는 경지.', conditions: '', notes: '' },
  { id: 'c9', sub: '방어', rank: '', name: '만독불침', aliases: [], desc: '모든 독이 침범하지 못함.', conditions: '', notes: '' },
  { id: 'c10', sub: '방어', rank: '', name: '도검불침', aliases: [], desc: '칼과 검이 침범하지 못함.', conditions: '', notes: '' },
  { id: 'c11', sub: '방어', rank: '', name: '한서불침', aliases: [], desc: '춥고 더움이 침범하지 못함.', conditions: '', notes: '' },
  { id: 'c13', sub: '성취', rank: '', name: '삼화취정', aliases: [], desc: '정, 기, 신 세 가지 꽃이 정수리에 모이는 경지.', conditions: '', notes: '' },
  { id: 'c14', sub: '성취', rank: '', name: '오기조원', aliases: [], desc: '오장의 다섯 기운이 근원으로 조화되는 경지.', conditions: '', notes: '' },
  { id: 'c16', sub: '성취', rank: '', name: '반박귀진', aliases: [], desc: '꾸밈을 버리고 본래의 진실로 돌아감.', conditions: '', notes: '' },
  { id: 'c15', sub: '성취', rank: '', name: '무극', aliases: [], desc: '극이 없는 경지. 어떠한 한계도 없는 상태.', conditions: '', notes: '' },
];
