import type { Art } from './types';

export const DEFAULT_ARTS: Art[] = [
  {
    id: 'ma9',
    faction: '정파',
    type: '병기법',
    name: '태극혜검',
    tag: '무당파',
    desc: '무당파의 대표 검법. 태극의 원리를 검에 담아 부드러움으로 강함을 꺾는 무공.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma8',
    faction: '정파',
    type: '권각법',
    name: '태극권',
    tag: '무당파',
    desc: '무당파의 대표 권법. 부드러움으로 강함을 제압하는 이유극강의 원리.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma10',
    faction: '정파',
    type: '병기법',
    name: '이십사수매화검법',
    tag: '화산파',
    desc: '화산파의 대표 검법. 매화가 피어나듯 화려하고 정밀한 24수의 검초.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma14',
    faction: '정파',
    type: '병기법',
    name: '천뢰검법',
    tag: '남궁세가',
    desc: '뇌기를 검에 실어 내리치는 가전검법. 고통을 줄이는 구결이 없어 극도로 익히기 까다로움. 대성 시 눈동자가 금색으로 변함.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '세가 내에서도 사양 추세.',
  },
  {
    id: 'ma15',
    faction: '정파',
    type: '병기법',
    name: '제왕검형',
    tag: '남궁세가',
    desc: '내공으로 상대가 운신할 공간 자체를 막아버리는 가전검법. 유력 후계자부터 전수.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma16',
    faction: '정파',
    type: '병기법',
    name: '천뢰제왕검형',
    tag: '남궁세가',
    desc: '천뢰검법과 제왕검형을 하나로 합친 합일검법. 제왕검형으로 가두고 뇌기로 마무리.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma11',
    faction: '정파',
    type: '병기법',
    name: '타구봉법',
    tag: '개방',
    desc: '개방 방주만이 전수받는 봉법. 개의 머리를 때리는 듯한 독특한 궤적.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma12',
    faction: '정파',
    type: '권각법',
    name: '항룡십팔장',
    tag: '개방',
    desc: '개방의 최강 장법. 18초식으로 구성된 강맹한 장력의 무공.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma13',
    faction: '정파',
    type: '암기법',
    name: '만천화우',
    tag: '사천당가',
    desc: '사천당가의 대표 암기술. 꽃비처럼 쏟아지는 수백 개의 암기로 범위를 제압.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma3',
    faction: '무소속',
    type: '신보법',
    name: '이형환위',
    tag: '최상급 경공',
    desc: '단순히 빨리 뛰는 경공을 넘어선 순간이동에 가까운 상급 신법. 잔상을 남기며 위치를 바꿔치기하는 기술.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '역골공과 병행하면 변장과 이동을 동시에 활용 가능.',
  },
  {
    id: 'ma4',
    faction: '무소속',
    type: '신보법',
    name: '허공답보',
    tag: '최상급 경공',
    desc: '허공을 밟으며 이동하는 최상위 경공. 화경 이상에서 구사 가능한 전설적 신법.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'n5',
    faction: '무소속',
    type: '특수법',
    name: '흡성대법',
    tag: '흡공 계열',
    desc: '상대의 내공을 강제로 흡수하여 자신의 것으로 만드는 절학. 특정 세력에 속하지 않는 금기의 무공.',
    traits: ['타인의 내공을 직접 흡수', '빠른 축적이 가능하나 뒤엉킬 위험'],
    merits: '축적 속도가 매우 빠름.',
    demerits: '이질적 내공 충돌 시 주화입마 위험.',
    details: [],
    notes: '',
  },
  {
    id: 'ma5',
    faction: '무소속',
    type: '특수법',
    name: '격공섭물',
    tag: '운기',
    desc: '진기를 발출하여 먼 거리의 물건을 끌어당기거나 밀어내는 기술. 화경 이상에서 구사 가능.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma2',
    faction: '무소속',
    type: '특수법',
    name: '축골술',
    tag: '특수 체술',
    desc: '역골공의 하위 개념. 뼈와 근육을 압축해 몸집을 줄이는 기술. 잠입과 암살의 필수 무공.',
    traits: [],
    merits: '',
    demerits: '',
    details: [],
    notes: '',
  },
  {
    id: 'ma1',
    faction: '무소속',
    type: '특수법',
    name: '역골공',
    tag: '특수 체술',
    desc: '인체의 뼈 마디마디를 탈구시키거나 수축시켜 체형을 자유자재로 변형하는 무공.',
    traits: [],
    merits: '',
    demerits: '',
    details: [
      { l: '탈출', t: '포박 시 뼈를 어긋나게 해 빠져나옴.' },
      { l: '공격', t: '팔 길이를 순간 늘려 타격.' },
      { l: '방어', t: '급소 위치를 비틀어 치명상을 면함.' },
    ],
    notes: '하위 개념으로 축골술이 있음.',
  },
];
